comments:
  gitment: 
    css: https://cdn.jsdelivr.net/gh/theme-next/theme-next-gitment@1/default.css 
    js: https://cdn.jsdelivr.net/gh/theme-next/theme-next-gitment@1/gitment.browser.js
  gitalk: 
    css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
    js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

render:
  ts: tsconfig.json